# Generated by Django 3.2 on 2023-12-29 17:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='excerpt_notes',
        ),
        migrations.AddField(
            model_name='reservation',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='reservation',
            name='date_of_booking',
            field=models.DateField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='reservation',
            name='nick_name',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='reservation',
            name='time_of_booking',
            field=models.IntegerField(choices=[(0, '12.30am'), (1, '1.00pm')], default=0),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='full_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
