# Generated by Django 3.2 on 2023-12-31 22:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0002_auto_20231229_1744'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reservation',
            options={'ordering': ['created_on']},
        ),
    ]
