# Generated by Django 3.2 on 2023-12-31 23:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0004_auto_20231231_2309'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='num_of_guests',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
