# Generated by Django 3.2 on 2024-01-01 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0005_alter_reservation_num_of_guests'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='time_of_booking',
            field=models.IntegerField(choices=[(None, '---------'), (0, '12:30am'), (1, '1:00pm'), (2, '1:30pm'), (3, '2:00pm'), (4, '2:30pm'), (5, '8:00pm'), (6, '8:30pm'), (7, '9:00pm'), (8, '9:30pm')], default=0),
        ),
    ]
