# Generated by Django 3.2 on 2024-01-01 14:27

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0006_alter_reservation_time_of_booking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='time_of_booking',
            field=models.IntegerField(choices=[(None, '---------'), (0, datetime.datetime(1900, 1, 1, 12, 55, tzinfo=utc)), (1, datetime.datetime(1900, 1, 1, 13, 25, tzinfo=utc)), (2, datetime.datetime(1900, 1, 1, 13, 55, tzinfo=utc)), (3, datetime.datetime(1900, 1, 1, 14, 25, tzinfo=utc)), (4, datetime.datetime(1900, 1, 1, 14, 55, tzinfo=utc)), (5, datetime.datetime(1900, 1, 1, 20, 25, tzinfo=utc)), (6, datetime.datetime(1900, 1, 1, 20, 55, tzinfo=utc)), (7, datetime.datetime(1900, 1, 1, 21, 25, tzinfo=utc)), (8, datetime.datetime(1900, 1, 1, 21, 55, tzinfo=utc))], default=0),
        ),
    ]
