# Generated by Django 3.2 on 2024-01-01 14:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0007_alter_reservation_time_of_booking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='time_of_booking',
            field=models.IntegerField(choices=[(None, '---------'), (0, datetime.time(12, 30)), (1, datetime.time(13, 0)), (2, datetime.time(13, 30)), (3, datetime.time(14, 0)), (4, datetime.time(14, 30)), (5, datetime.time(20, 0)), (6, datetime.time(20, 30)), (7, datetime.time(21, 0)), (8, datetime.time(21, 30))], default=0),
        ),
    ]
