# Generated by Django 3.2 on 2024-01-01 14:57

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0008_alter_reservation_time_of_booking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='created_on',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='date_of_booking',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
