# Generated by Django 3.2 on 2024-01-01 16:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0011_auto_20240101_1635'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='num_of_guests',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
